# Generated by Django 3.0.7 on 2020-07-02 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(null=True, related_name='_user_friend_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
