# Generated by Django 3.0.7 on 2020-07-02 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Type a greeting here', max_length=500, null=True)),
                ('date_field', models.DateTimeField(auto_now_add=True)),
                ('background_color', models.CharField(choices=[('LightSkyBlue', '00BFFF'), ('LightSalmon', 'FFA07A'), ('Lavender', 'E6E6FA'), ('PaleGreen', '98FB98')], default='', max_length=20)),
                ('border', models.CharField(choices=[('DottedBorder', 'DottedBorder'), ('DashedBorder', 'DashedBorder'), ('SolidBorder', 'SolidBorder'), ('NoBorder', 'NoBorder')], default='', max_length=20)),
                ('font', models.CharField(choices=[('Cambria', 'Cambria'), ('Verdana', 'Verdana'), ('Copperplate', 'Copperplate'), ('Arial', 'Arial'), ('Perpetua', 'Perpetua')], default='', max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='card_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
