# Generated by Django 3.0.7 on 2020-07-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('PaleGreen', '98FB98'), ('LightSalmon', 'FFA07A'), ('LightSkyBlue', '00BFFF'), ('Lavender', 'E6E6FA')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('SolidBorder', 'SolidBorder'), ('DashedBorder', 'DashedBorder'), ('NoBorder', 'NoBorder'), ('DottedBorder', 'DottedBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Verdana', 'Verdana'), ('Perpetua', 'Perpetua'), ('Cambria', 'Cambria'), ('Copperplate', 'Copperplate'), ('Arial', 'Arial')], default='', max_length=20),
        ),
    ]
