# Generated by Django 3.0.7 on 2020-07-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200702_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('Lavender', 'E6E6FA'), ('PaleGreen', '98FB98'), ('LightSalmon', 'FFA07A'), ('LightSkyBlue', '00BFFF')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('NoBorder', 'NoBorder'), ('DashedBorder', 'DashedBorder'), ('SolidBorder', 'SolidBorder'), ('DottedBorder', 'DottedBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Verdana', 'Verdana'), ('Cambria', 'Cambria'), ('Perpetua', 'Perpetua'), ('Copperplate', 'Copperplate'), ('Arial', 'Arial')], default='', max_length=20),
        ),
    ]
