# Generated by Django 3.0.7 on 2020-07-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200702_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('98FB98', 'PaleGreen'), ('FFA07A', 'LightSalmon'), ('E6E6FA', 'Lavender'), ('00BFFF', 'LightSkyBlue')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('SolidBorder', 'SolidBorder'), ('DottedBorder', 'DottedBorder'), ('NoBorder', 'NoBorder'), ('DashedBorder', 'DashedBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Cambria', 'Cambria'), ('Copperplate', 'Copperplate'), ('Arial', 'Arial'), ('Perpetua', 'Perpetua'), ('Verdana', 'Verdana')], default='', max_length=20),
        ),
    ]
