# Generated by Django 3.0.7 on 2020-07-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200702_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('E6E6FA', 'Lavender'), ('98FB98', 'PaleGreen'), ('FFA07A', 'LightSalmon'), ('00BFFF', 'LightSkyBlue')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('SolidBorder', 'SolidBorder'), ('DashedBorder', 'DashedBorder'), ('NoBorder', 'NoBorder'), ('DottedBorder', 'DottedBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Cambria', 'Cambria'), ('Copperplate', 'Copperplate'), ('Perpetua', 'Perpetua'), ('Verdana', 'Verdana'), ('Arial', 'Arial')], default='', max_length=20),
        ),
    ]
