# Generated by Django 3.0.7 on 2020-07-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200702_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('PaleGreen', 'PaleGreen'), ('LightSkyBlue', 'LightSkyBlue'), ('LightSalmon', 'LightSalmon'), ('Lavender', 'Lavender')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('NoBorder', 'NoBorder'), ('DashedBorder', 'DashedBorder'), ('SolidBorder', 'SolidBorder'), ('DottedBorder', 'DottedBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Verdana', 'Verdana'), ('Arial', 'Arial'), ('Copperplate', 'Copperplate'), ('Perpetua', 'Perpetua'), ('Cambria', 'Cambria')], default='', max_length=20),
        ),
    ]
