# Generated by Django 3.0.7 on 2020-07-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200702_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('Lavender', 'Lavender'), ('LightSkyBlue', 'LightSkyBlue'), ('LightSalmon', 'LightSalmon'), ('PaleGreen', 'PaleGreen')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('DashedBorder', 'DashedBorder'), ('DottedBorder', 'DottedBorder'), ('SolidBorder', 'SolidBorder'), ('NoBorder', 'NoBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Copperplate', 'Copperplate'), ('Arial', 'Arial'), ('Cambria', 'Cambria'), ('Perpetua', 'Perpetua'), ('Verdana', 'Verdana')], default='', max_length=20),
        ),
    ]
