# Generated by Django 3.0.7 on 2020-07-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200702_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('SolidBorder', 'SolidBorder'), ('DottedBorder', 'DottedBorder'), ('NoBorder', 'NoBorder'), ('DashedBorder', 'DashedBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Copperplate', 'Copperplate'), ('Cambria', 'Cambria'), ('Verdana', 'Verdana'), ('Perpetua', 'Perpetua')], default='', max_length=20),
        ),
    ]
