# Generated by Django 3.0.7 on 2020-07-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200702_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('Lavender', 'Lavender'), ('LightSalmon', 'LightSalmon'), ('PaleGreen', 'PaleGreen'), ('LightSkyBlue', 'LightSkyBlue')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('DashedBorder', 'DashedBorder'), ('SolidBorder', 'SolidBorder'), ('NoBorder', 'NoBorder'), ('DottedBorder', 'DottedBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Perpetua', 'Perpetua'), ('Copperplate', 'Copperplate'), ('Cambria', 'Cambria')], default='', max_length=20),
        ),
    ]
