# Generated by Django 3.0.7 on 2020-07-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200703_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('PaleGreen', 'PaleGreen'), ('LightSalmon', 'LightSalmon'), ('LightSkyBlue', 'LightSkyBlue'), ('Lavender', 'Lavender')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Perpetua', 'Perpetua'), ('Copperplate', 'Copperplate'), ('Verdana', 'Verdana'), ('Cambria', 'Cambria')], default='', max_length=20),
        ),
    ]
