# Generated by Django 3.0.7 on 2020-07-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200703_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('LightSalmon', 'LightSalmon'), ('PaleGreen', 'PaleGreen'), ('Lavender', 'Lavender'), ('LightSkyBlue', 'LightSkyBlue')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('DashedBorder', 'DashedBorder'), ('DottedBorder', 'DottedBorder'), ('NoBorder', 'NoBorder'), ('SolidBorder', 'SolidBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Copperplate', 'Copperplate'), ('Verdana', 'Verdana'), ('Perpetua', 'Perpetua'), ('Cambria', 'Cambria'), ('Arial', 'Arial')], default='', max_length=20),
        ),
    ]
