# Generated by Django 3.0.7 on 2020-07-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200703_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('PaleGreen', 'PaleGreen'), ('Lavender', 'Lavender'), ('LightSalmon', 'LightSalmon'), ('LightSkyBlue', 'LightSkyBlue')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('DashedBorder', 'DashedBorder'), ('DottedBorder', 'DottedBorder'), ('SolidBorder', 'SolidBorder'), ('NoBorder', 'NoBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Copperplate', 'Copperplate'), ('Arial', 'Arial'), ('Perpetua', 'Perpetua'), ('Cambria', 'Cambria'), ('Verdana', 'Verdana')], default='', max_length=20),
        ),
    ]
