# Generated by Django 3.0.7 on 2020-07-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200703_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('Lavender', 'Lavender'), ('PaleGreen', 'PaleGreen'), ('LightSalmon', 'LightSalmon'), ('LightSkyBlue', 'LightSkyBlue')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('SolidBorder', 'SolidBorder'), ('NoBorder', 'NoBorder'), ('DashedBorder', 'DashedBorder'), ('DottedBorder', 'DottedBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Copperplate', 'Copperplate'), ('Cambria', 'Cambria'), ('Perpetua', 'Perpetua'), ('Verdana', 'Verdana')], default='', max_length=20),
        ),
    ]
