# Generated by Django 3.0.7 on 2020-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200703_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('Lavender', 'Lavender'), ('LightSalmon', 'LightSalmon'), ('PaleGreen', 'PaleGreen'), ('LightSkyBlue', 'LightSkyBlue')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('DottedBorder', 'DottedBorder'), ('NoBorder', 'NoBorder'), ('SolidBorder', 'SolidBorder'), ('DashedBorder', 'DashedBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Perpetua', 'Perpetua'), ('Cambria', 'Cambria'), ('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Copperplate', 'Copperplate')], default='', max_length=20),
        ),
    ]
