# Generated by Django 3.0.7 on 2020-07-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200706_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('SolidBorder', 'SolidBorder'), ('NoBorder', 'NoBorder'), ('DashedBorder', 'DashedBorder'), ('DottedBorder', 'DottedBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Verdana', 'Verdana'), ('Arial', 'Arial'), ('Copperplate', 'Copperplate'), ('Perpetua', 'Perpetua'), ('Cambria', 'Cambria')], default='', max_length=20),
        ),
    ]
