# Generated by Django 3.0.7 on 2020-07-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200706_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('PaleGreen', 'PaleGreen'), ('LightSalmon', 'LightSalmon'), ('LightSkyBlue', 'LightSkyBlue'), ('Lavender', 'Lavender')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('SolidBorder', 'SolidBorder'), ('DashedBorder', 'DashedBorder'), ('NoBorder', 'NoBorder'), ('DottedBorder', 'DottedBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Cambria', 'Cambria'), ('Verdana', 'Verdana'), ('Perpetua', 'Perpetua'), ('Copperplate', 'Copperplate')], default='', max_length=20),
        ),
    ]
