# Generated by Django 3.0.7 on 2020-07-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200706_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('LightSalmon', 'LightSalmon'), ('PaleGreen', 'PaleGreen'), ('Lavender', 'Lavender'), ('LightSkyBlue', 'LightSkyBlue')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('DottedBorder', 'DottedBorder'), ('DashedBorder', 'DashedBorder'), ('SolidBorder', 'SolidBorder'), ('NoBorder', 'NoBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Copperplate', 'Copperplate'), ('Perpetua', 'Perpetua'), ('Cambria', 'Cambria'), ('Arial', 'Arial'), ('Verdana', 'Verdana')], default='', max_length=20),
        ),
    ]
