# Generated by Django 3.0.7 on 2020-07-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200706_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('PaleGreen', 'PaleGreen'), ('LightSalmon', 'LightSalmon'), ('LightSkyBlue', 'LightSkyBlue'), ('Lavender', 'Lavender')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('SolidBorder', 'SolidBorder'), ('DottedBorder', 'DottedBorder'), ('DashedBorder', 'DashedBorder'), ('NoBorder', 'NoBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Verdana', 'Verdana'), ('Perpetua', 'Perpetua'), ('Copperplate', 'Copperplate'), ('Cambria', 'Cambria'), ('Arial', 'Arial')], default='', max_length=20),
        ),
    ]
