# Generated by Django 3.0.7 on 2020-07-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200706_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('LightSalmon', 'LightSalmon'), ('PaleGreen', 'PaleGreen'), ('LightSkyBlue', 'LightSkyBlue'), ('Lavender', 'Lavender')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('SolidBorder', 'SolidBorder'), ('DashedBorder', 'DashedBorder'), ('NoBorder', 'NoBorder'), ('DottedBorder', 'DottedBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Copperplate', 'Copperplate'), ('Verdana', 'Verdana'), ('Perpetua', 'Perpetua'), ('Cambria', 'Cambria'), ('Arial', 'Arial')], default='', max_length=20),
        ),
    ]
