# Generated by Django 3.0.7 on 2020-07-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200706_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('LightSalmon', 'LightSalmon'), ('Lavender', 'Lavender'), ('LightSkyBlue', 'LightSkyBlue'), ('PaleGreen', 'PaleGreen')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('SolidBorder', 'SolidBorder'), ('DashedBorder', 'DashedBorder'), ('DottedBorder', 'DottedBorder'), ('NoBorder', 'NoBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Copperplate', 'Copperplate'), ('Arial', 'Arial'), ('Perpetua', 'Perpetua'), ('Verdana', 'Verdana'), ('Cambria', 'Cambria')], default='', max_length=20),
        ),
    ]
