# Generated by Django 3.0.7 on 2020-07-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200706_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('Lavender', 'Lavender'), ('LightSalmon', 'LightSalmon'), ('PaleGreen', 'PaleGreen'), ('LightSkyBlue', 'LightSkyBlue')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Copperplate', 'Copperplate'), ('Cambria', 'Cambria'), ('Verdana', 'Verdana'), ('Perpetua', 'Perpetua'), ('Arial', 'Arial')], default='', max_length=20),
        ),
    ]
