# Generated by Django 3.0.7 on 2020-07-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200706_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('PaleGreen', 'PaleGreen'), ('LightSalmon', 'LightSalmon'), ('Lavender', 'Lavender'), ('LightSkyBlue', 'LightSkyBlue')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('SolidBorder', 'SolidBorder'), ('DashedBorder', 'DashedBorder'), ('NoBorder', 'NoBorder'), ('DottedBorder', 'DottedBorder')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Perpetua', 'Perpetua'), ('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Copperplate', 'Copperplate'), ('Cambria', 'Cambria')], default='', max_length=20),
        ),
    ]
