# Generated by Django 3.0.7 on 2020-07-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200707_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('LightSkyBlue', 'LightSkyBlue'), ('Lavender', 'Lavender'), ('LightSalmon', 'LightSalmon'), ('PaleGreen', 'PaleGreen')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Copperplate', 'Copperplate'), ('Perpetua', 'Perpetua'), ('Cambria', 'Cambria'), ('Verdana', 'Verdana')], default='', max_length=20),
        ),
    ]
