# Generated by Django 3.0.7 on 2020-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200707_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('NoBorder', 'NoBorder'), ('SolidBorder', 'SolidBorder'), ('DottedBorder', 'DottedBorder'), ('DashedBorder', 'DashedBorder')], default='NoBorder', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Cambria', 'Cambria'), ('Perpetua', 'Perpetua'), ('Copperplate', 'Copperplate'), ('Verdana', 'Verdana'), ('Arial', 'Arial')], default='Perpetua', max_length=20),
        ),
    ]
