# Generated by Django 3.0.7 on 2020-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200707_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('LightSalmon', 'LightSalmon'), ('LightSkyBlue', 'LightSkyBlue'), ('Lavender', 'Lavender'), ('PaleGreen', 'PaleGreen')], default='LightSkyBlue', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('DashedBorder', 'DashedBorder'), ('DottedBorder', 'DottedBorder'), ('NoBorder', 'NoBorder'), ('SolidBorder', 'SolidBorder')], default='NoBorder', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Perpetua', 'Perpetua'), ('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Copperplate', 'Copperplate'), ('Cambria', 'Cambria')], default='Perpetua', max_length=20),
        ),
    ]
