# Generated by Django 3.0.7 on 2020-07-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200707_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(choices=[('LightSkyBlue', 'LightSkyBlue'), ('PaleGreen', 'PaleGreen'), ('Lavender', 'Lavender'), ('LightSalmon', 'LightSalmon')], default='LightSkyBlue', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('NoBorder', 'NoBorder'), ('DottedBorder', 'DottedBorder'), ('DashedBorder', 'DashedBorder'), ('SolidBorder', 'SolidBorder')], default='NoBorder', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Perpetua', 'Perpetua'), ('Copperplate', 'Copperplate'), ('Cambria', 'Cambria'), ('Arial', 'Arial'), ('Verdana', 'Verdana')], default='Perpetua', max_length=20),
        ),
    ]
